package Lexer;

public class Gramatica {

	public final static String
		VOID = "void",
		FIM = "fim",
		VAR = "var",
		ID = "id",
		LETTER = "letter",
		NUMBER = "number",
		IF = "if",
		ENDIF = "endif",
		THEN = "then",
		ELSE= "else",
		WHILE = "while",
		MAIS = "mais",
		MENOS= "menos",
		PARENTESESD = "parentesesd",
		PARENTESESE = "parentesese",
		MULTIPLICACAO = "multiplicacao",
		MODULO= "modulo",
		DIVISAO = "divisao",
		MAIOR = "maior",
		MENOR = "menor",
		MENORIGUAL = "menorigual",
		MAIORIGUAL = "maiorigual",
		ATRIBUICAO = "atribuicao",
		DIFERENTE = "diferente",
		IGUAL = "igual",
		VIRGULA = "virgula",
		PONTOEVIRGULA = "pontoevirgula",
		PONTO = "ponto",
		BEGIN = "begin",
		END = "end",	
		READ = "read",
		WRITE = "write",
		INTEGER = "integer",
		BOOLEAN = "boolean",
		CHAR = "char",
		OR = "or",
		AND = "and",
		TRUE = "true",
		DIGIT = "digit",
		NOT = "not",
		FALSE = "false",
		DOISPONTOS = "doispontos";
	
}
